---
- name : Automatize vmware
  hosts: localhost
  vars_files:
    - credential_vc.yml

  tasks:
  - name: Create Datacenter
    local_action:
      module: vmware_datacenter
      hostname: "{{ ip_vc }}"
      username: "{{ username_vc }}"
      password: "{{ pass_vc }}"
      datacenter_name: "{{ dc_name }}"
      state: present
      validate_certs: no
    tags: dc

  - name: Create Cluster with HA enabled
    local_action:
      module: vmware_cluster
      hostname: "{{ ip_vc }}"
      username: "{{ username_vc }}"
      password: "{{ pass_vc }}"
      datacenter_name: "{{ dc_name }}"
      cluster_name: "{{ cluster_name }}"
      enable_ha: yes
      enable_drs: yes
      enable_vsan: no
      validate_certs: no
    tags: cluster

  - name: Add ESXi Host to vCenter
    local_action:
      module: vmware_host
      hostname: '{{ ip_vc }}'
      username: '{{ username_vc }}'
      password: '{{ pass_vc }}'
      datacenter_name: "{{ dc_name }}"
      cluster_name: "{{ cluster_name }}"
      esxi_hostname: '{{ item }}'
      esxi_username: '{{ esxi_username }}'
      esxi_password: '{{ esxi_password }}'
      state: present
      validate_certs: no
    with_items:
      - "{{ ip_esxi1 }}"
      - "{{ ip_esxi2 }}"
    tags: hosts
