---
- name : Automatize vmware
  hosts: localhost
  
  tasks:
  - name: Create VM
    local_action:
      module: vmware_guest
      hostname: vcenter
      username: "{{ username_vc }}"
      password: "{{ pass_vc }}"
      validate_certs: no
      name: "{{ vm_name }}"
      state: poweredoff
      folder: /
      datacenter: XPERT-LAB GOLD
      guest_id: centos64Guest
      disk:
      - size_gb: "{{ disk_gb }}"
        type: thin
        datastore: SILVER-STORAGE
      networks:
      - name: VM Network
        type: dhcp
      hardware:
        memory_mb: "{{ memory_mb }}"
        num_cpus: "{{ cpu_n }}"
        scsi: paravirtual
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: False
    tags: vm
