---
- name : Automatize vmware
  hosts: localhost
    vars_file: credential_vc.yml
  
  tasks:
  - name: Create VM
    local_action:
      module: vmware_guest
      hostname: "{{ ip_vc }}"
      username: "{{ username_vc }}"
      password: "{{ pass_vc }}"
      validate_certs: no
      name: "{{ vm_name }}"
      state: poweredoff
      folder: /
      datacenter: "{{ dc_name }}"
      guest_id: centos64Guest
      disk:
      - size_gb: 10
        type: thin
        datastore: "{{ dest_ds }}"
      networks:
      - name: VM Network
        type: dhcp
      hardware:
        memory_mb: "{{ memory_mb }}"
        num_cpus: "{{ cpu_n }}"
        scsi: paravirtual
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: False
    tags: vm
